dist: xenial
language: python
python:
- '3.6'
install: pip install -r requirements.txt
script: pytest -v --cov . --cov-report term-missing --cov-fail-under=100
deploy:
  skip_cleanup: true
  provider: script
  script: fab -i new_aws.pem -H ubuntu@13.48.49.203 deploy
  on:
    branc: master
before_install:
- openssl aes-256-cbc -K $encrypted_2ebe3b6afdb1_key -iv $encrypted_2ebe3b6afdb1_iv
  -in new_aws.pem.enc -out new_aws.pem -d
