dist: xenial
language: python
python:
- '3.6'
install: pip install -r requirements.txt
script: pytest -v --cov . --cov-report term-missing --cov-fail-under=100

before_install:
- openssl aes-256-cbc -K $encrypted_3a7458c04994_key -iv $encrypted_3a7458c04994_iv
  -in xx3u.pem.enc -out xx3u.pem -d

deploy:
  provider: script
  script: fab -i xx3u.pem -H ubuntu@134.209.228.212 deploy
  on:
    branc: master
