dist: xenial
language: python
python:
- '3.6'
before_install:
- openssl aes-256-cbc -K $encrypted_2ebe3b6afdb1_key -iv $encrypted_2ebe3b6afdb1_iv
  -in xx3u.pem.enc -out ./xx3u.pem -d
install: pip install -r requirements.txt
script: pytest -v --cov . --cov-report term-missing --cov-fail-under=100
deploy:
  skip_cleanup: true
  provider: script
  script: fab -i xx3u.pem -H ubuntu@13.53.76.207 deploy
  on:
    branc: master
