# Generated by Django 2.2 on 2019-04-14 05:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('django_module', '0007_auto_20190414_0505'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='customer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='django_module.Customer'),
            preserve_default=False,
        ),
    ]
