# Generated by Django 2.2 on 2019-04-08 18:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('django_module', '0008_order_customer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='customer',
        ),
    ]
